### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by yijiangh** [edfan/firehose#12]
![image](https://user-images.githubusercontent.com/11905844/91317041-89fecd80-e787-11ea-8fd3-45c0e15ce712.png)

Google search tells me this has to be done on the developer's side. Would you mind resolving this?

**Comment by julianstanley** [comment]
May be easier (or maybe in addition?) to just package the schedule data into a .csv or .ics and have users upload that data into gcal themselves? 

Rather than or in addition to relying on the API

**Comment by edfan** [comment]
This is fixed! (as of September, lol)

.ics export would be cool, I remember looking into this years ago and deciding it wasn't worth it.
