### ISSUE TITLE
Automate schedule updates

### ISSUE THREAD

**Issue by edfan** [edfan/firehose#13]
I'm mostly writing this down for the sake of writing it down.

To pull in the latest version of the catalog, as of 2020-12:

in new_scripts/, run coursews.py, sublist_ws.py, combiner_ws.py in that order
cp full.json ../www/full.js

I should write a simple bash script to do this in one step, and then maybe automate it?

**Comment by cjquines** [comment]
to run combiner_ws.py, also need to scrape evaluations. not sure what the legit method is, but i did:

- make a folder firehose-priv, copy old_scripts/evalscraper.py to firehose-priv/evalscraper.py
- update username, terms, make a password file with password
- run evalscraper.py, then run old_scripts/eval_to_json.py
