### ISSUE TITLE
Rerun eval_scraper.py

### ISSUE THREAD

**Issue by edfan** [edfan/firehose#4]
It would be great if someone could run [eval_scraper.py](https://github.com/edfan/firehose/blob/master/old_scripts/eval_scraper.py) (requires MIT login). You'll need:

- a copy of [chromedriver](https://chromedriver.chromium.org/) in your PATH
- change 'username' to your username
- add a file called 'password' with your Athena password

If you could run it with terms = ['2019SP', '2019SU', '2020FA', '2020JA', '2020SP'], that would be great. It's quite possible that it'll break horribly; let me know if it does.

Please don't make this data public; feel free to email me at the link on the website.

**Comment by mdlu** [comment]
I'm almost done running this and will send to you soon!

**Comment by edfan** [comment]
Done. Thanks @mdlu!
