### ISSUE TITLE
Incorrect instructors?

### ISSUE THREAD

**Issue by synicalsyntax** [edfan/firehose#5]
First off, thanks so much for updating the site! The entire undergrad class is super excited to see the updated course offerings and we were really struggling with scheduling classes without your site.

There's something I noticed: it seems that the instructors for certain courses don't match up with what the catalog currently says. For example,

- 6.003 lists "Instructors: D. M. Freeman, A. Hartz" (who taught in 2019),  but the catalog says "J. Kong" is teaching the course.
- 6.036 lists "Instructors: D. S. Boning, P. Jaillet,  L. P. Kaelbling", but the catalog says only "D. Boning" is teaching the course (2 other different instructors are listed along Boning on https://eecs.scripts.mit.edu/eduportal/who_is_teaching_what/F/2020/)

On the other hand, courses like 18.06 do reflect instructors correctly.

Would this be an issue with the data scraper picking up the wrong data or values not being updated in storage properly?

**Comment by edfan** [comment]
Hmm, that's a good point. I'm currently pulling in the fall_instructors field on [coursews](http://coursews.mit.edu/coursews/?term=2021FA), but it looks like in-charge is better at least for Course 6. Overall, it does seem like in-charge is better for the examples that I've looked at, so I'm going to push a change to switch to that.

**Comment by edfan** [comment]
Okay, resolved. (Might need to hard refresh to see the change.) I've changed the text to "In-charge:" for clarity.

Thanks for reporting this!
